language: erlang
otp_release:
  - 17.0
  - R16B03-1
  - R15B03
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script: "./rebar3 update && ./rebar3 ct"
branches:
  only:
    - master
notifications:
  email:
    - core@erlware.org
  irc:
    channels:
      - "irc.freenode.org#erlware"
    use_notice: true
    skip_join: true
